### ISSUE TITLE
Projects Page Design

### ISSUE THREAD

**Issue by Fcuervo21** [RafaGomezGlez/WebVisualization#22]
Projects page new design using

- [x] Adobe XD

- [x] HTML/CSS implementation

**Comment by Fcuervo21** [comment]
Basic UX Design for Projects Home Page, I decided to show our projects using cards.
![Projects-Home-Page](https://user-images.githubusercontent.com/63762598/119912850-de56f980-bf21-11eb-856a-769134bbb2aa.png)

**Comment by Fcuervo21** [comment]
Basic Responsive Design for Projects Home Page.
![Projects-Home-Page-Responsive](https://user-images.githubusercontent.com/63762598/119913195-e6636900-bf22-11eb-9446-887b1fc15ca4.png)

**Comment by RafaGomezGlez** [comment]
LGTM!
