### ISSUE TITLE
Basic UX Design

### ISSUE THREAD

**Issue by Fcuervo21** [RafaGomezGlez/WebVisualization#6]
- Logos
- Color palette
- Fonts
- Water Mark
- Images

**Comment by RafaGomezGlez** [comment]
**First version of the landing page.**
Missing: 
-Final logo
-Fonts
-Images
-Water Mark


![Página inicio](https://user-images.githubusercontent.com/61569733/116180466-92285780-a6de-11eb-9b11-ad8b57c97c49.png)

**Comment by Fcuervo21** [comment]
First Version Raven Design

![WebUX_V1](https://user-images.githubusercontent.com/63762598/116343303-ca489c80-a7a9-11eb-86c0-bead8f380e85.png)

**Comment by RafaGomezGlez** [comment]
We're choosing both designs in which we'll use the header and images distribution of the first one and the body of the second one as well as the footer
